CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"age" integer NOT NULL,
	"email" varchar(255) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"role" varchar(255) DEFAULT 'user' NOT NULL,
	"status" varchar(255) DEFAULT 'active' NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"isDeleted" boolean DEFAULT false NOT NULL,
	"isSuspended" boolean DEFAULT false NOT NULL,
	"isLocked" boolean DEFAULT false NOT NULL,
	"isEmailVerified" boolean DEFAULT false NOT NULL,
	"isPhoneVerified" boolean DEFAULT false NOT NULL,
	"isPremium" boolean DEFAULT false NOT NULL,
	"isTrial" boolean DEFAULT false NOT NULL,
	"isTrialExpired" boolean DEFAULT false NOT NULL,
	"isTrialStarted" boolean DEFAULT false NOT NULL,
	"isTrialEnded" boolean DEFAULT false NOT NULL,
	"credits" integer DEFAULT 0 NOT NULL,
	"creditsUsed" integer DEFAULT 0 NOT NULL,
	"creditsRemaining" integer DEFAULT 0 NOT NULL,
	"creditsExhausted" boolean DEFAULT false NOT NULL,
	"creditsExhaustedAt" timestamp,
	"creditsExhaustedReason" varchar(255) DEFAULT '' NOT NULL,
	"creditsExhaustedReasonDescription" varchar(255) DEFAULT '' NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
