import type { Metadata } from "next";
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion";

export const metadata: Metadata = {
    title: "FAQ | DeepPivot",
    description: "Frequently asked questions about DeepPivot — AI interview practice, career archetypes, pricing, and more.",
};

const FAQS = [
    {
        q: "What is DeepPivot?",
        a: "DeepPivot is an AI-powered career development platform that helps you practice job interviews with a real-time voice coach (Sarah, powered by ElevenLabs), discover your career archetype, build a personalized career roadmap, track job applications, and explore alternative education pathways.",
    },
    {
        q: "How does the AI voice interview work?",
        a: "You connect to a live voice session with Sarah, our ElevenLabs Conversational AI coach. She conducts a realistic interview using behavioral, technical, or situational questions tailored to your goals. Sessions are processed in real-time with under 800ms response latency. After the session, you receive an emotional intelligence report, a performance score, and actionable feedback.",
    },
    {
        q: "Is my audio recording stored permanently?",
        a: "No. Audio is processed in real-time during your session and is not permanently stored on our servers. Transcripts and AI-generated feedback reports are saved to your account so you can review your progress over time.",
    },
    {
        q: "What is a Career Archetype?",
        a: "Your Career Archetype is a behavioral trait model generated by our AI (using a custom BERT-based classification model). It groups you into one of several archetypes (e.g., The Visionary, The Builder, The Connector) based on patterns in your interview responses, helping you understand your natural strengths and growth areas.",
    },
    {
        q: "What browser or microphone do I need?",
        a: "DeepPivot's voice interview works in modern browsers (Chrome, Edge, Safari 15+, Firefox 120+). You'll need a microphone — USB, built-in, or Bluetooth headset all work. We recommend a quiet environment and wired audio for the best experience, though Bluetooth is fully supported.",
    },
    {
        q: "Is there a free plan?",
        a: "Yes. The free plan includes a limited number of AI interview sessions per month, access to your career archetype, the job tracker, and the education explorer. Paid plans (Pro and Enterprise) unlock unlimited sessions, advanced analytics, mentor connections, and priority support.",
    },
    {
        q: "How does the Job Marketplace work?",
        a: "Employers can post jobs on DeepPivot and reach learners who are actively developing their skills. When you apply through the marketplace, an application card is automatically created on your Job Tracker so you can follow your progress in one place. Applications submitted through DeepPivot are marked with a '✦ Via DeepPivot' badge.",
    },
    {
        q: "Can I use DeepPivot for technical interviews?",
        a: "Yes. You can select 'Technical' as your interview type when starting a session. Sarah will ask technical questions suitable for software engineering, data science, and other technical roles. Note that coding challenges (whiteboard-style) are not supported yet — the current format is verbal technical discussions.",
    },
    {
        q: "What is the Career Plan?",
        a: "The Career Plan is a draggable, milestone-based roadmap you build to track your career goals. You can set milestones, attach resources (articles, courses, tools), and mark progress. WDB (Workforce Development Board) clients can sync their IEP goals directly into their career plan.",
    },
    {
        q: "Can employers or coaches use DeepPivot?",
        a: "Yes. Employers can create company profiles and post jobs through the marketplace. Mentors and workforce development coaches have dedicated dashboards to track their cohorts, provide session feedback, and manage referrals.",
    },
    {
        q: "How do I cancel my subscription?",
        a: "You can cancel your subscription at any time from your Billing settings page (/dashboard/billing). Your plan remains active until the end of the current billing period. We don't offer refunds for unused time, but you won't be charged again after cancellation.",
    },
    {
        q: "How do I contact support?",
        a: "You can reach us through our Contact page, or email hello@deeppivot.com directly. We aim to respond within 1–2 business days.",
    },
];

export default function FAQPage() {
    return (
        <div className="min-h-screen bg-background pt-24 pb-12">
            <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
                <div className="mb-10 text-center">
                    <h1 className="text-3xl font-bold tracking-tight mb-3">Frequently Asked Questions</h1>
                    <p className="text-muted-foreground">
                        Everything you need to know about DeepPivot. Can&apos;t find your answer?{" "}
                        <a href="/contact" className="text-primary hover:underline transition-all">Contact us.</a>
                    </p>
                </div>

                <Accordion type="single" collapsible className="space-y-2">
                    {FAQS.map((faq, i) => (
                        <AccordionItem
                            key={i}
                            value={`item-${i}`}
                            className="rounded-xl border bg-card px-5"
                        >
                            <AccordionTrigger className="text-sm font-medium text-left py-4 hover:no-underline">
                                {faq.q}
                            </AccordionTrigger>
                            <AccordionContent className="text-sm text-muted-foreground pb-4 leading-relaxed">
                                {faq.a}
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            </div>
        </div>
    );
}
